[tool.poetry]
name = "protokoll2nextcloud"
version = "0.1.0"
description = ""
authors = ["Florian Katerndhal <florian@katerndahl.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
